spring:
  application:
    name: catalog-service

spanner:
  project-id: ${SPANNER_PROJECT:local-project}
  instance-id: ${SPANNER_INSTANCE:local-instance}
  database-id: ${SPANNER_DATABASE:local-db}
  emulator-enabled: ${SPANNER_EMULATOR_ENABLED:true}
  emulator-host: ${SPANNER_EMULATOR_HOST:localhost:9010}

